### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kivervinicius** [Pedro-Souza/value-coins#6]
On run the command on terminal
`$ value-coins --coin BTC --all`
```

Error: Error on consulting Bittrex api url (https://bittrex.com/api/v1.1/public/getmarketsummary?market=btc-BTC).
INVALID_MARKET
    at /usr/lib/node_modules/value-coins/dist/bittrexApi.js:13:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
[!] Poloniex [+]
TypeError: Cannot read property 'last' of undefined
    at /usr/lib/node_modules/value-coins/dist/coins.js:12:76
    at process._tickCallback (internal/process/next_tick.js:103:7)

```

**Comment by Pedro-Souza** [comment]
It's not a error, the api just not list btc. I not filtered this. :/ 
more is already in dev. Thanks!!
